name: CI-stage uction

on:
  push:
    branches:
      - master

env:
  # Enable this for additional debug logging
  ACTIONS_RUNNER_DEBUG: true 

jobs:
  migrate:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: create CICDscripts directory 
        run: |
          set -e 
          sudo mkdir -p /home/accuityGHR/CICDscripts && sudo chmod -R 777 /home/accuityGHR/CICDscripts && cp -r CICDscripts/* /home/accuityGHR/CICDscripts
      
      - name: create Migrations SQL directory 
        run: |
          set -e 
          sudo mkdir -p /home/accuityGHR/Migrations && sudo chmod -R 777 /home/accuityGHR/Migrations && cp -r Migrations/* /home/accuityGHR/Migrations/  

      - name: move SQL to be executed 
        run: |
          set -e
          sudo mkdir -p /home/accuityGHR/sql_stage  && sudo chmod 777 /home/accuityGHR/sql_stage 
          sudo bash /home/accuityGHR/CICDscripts/MoveMigrationsSqlScripts.sh "/home/accuityGHR/sql_stage"

      - name: Set up Flyway
        run: |
          set -e
          sudo mkdir -p /usr/local/bin/flyway